version: "3.6"
services:
  zoo1:
    container_name: zoo1
    image: zookeeper:latest
    restart: always
    hostname: zoo1
    ports:
      - "2181:2181"
    networks:
      kafka:
        ipv4_address: 172.22.201.11
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo2:
    container_name: zoo2
    image: zookeeper:latest
    restart: always
    hostname: zoo2
    ports:
      - "2182:2181"

    networks:
      kafka:
        ipv4_address: 172.22.201.12
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo3:
    container_name: zoo3
    image: zookeeper:latest
    restart: always
    hostname: zoo3
    ports:
      - "2183:2181"
    networks:
      kafka:
        ipv4_address: 172.22.201.13
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  kafka-01:
    container_name: kafka-01
    image: wurstmeister/kafka:2.13-2.8.1
    restart: always
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - "9092:9092"
    networks:
      kafka:
        ipv4_address: 172.22.201.14
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.140.20.54
      JMX_PORT: 9999
      HOST_IP: 10.140.20.54
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 0
#      KAFKA_HEAP_OPTS: "-Xmx8192M -Xms8192M"
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LISTENERS: PLAINTEXT://kafka-01:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.140.20.54:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183

  kafka-02:
    container_name: kafka-02
    image: wurstmeister/kafka:2.13-2.8.1
    restart: always
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - "9093:9092"
    networks:
      kafka:
        ipv4_address: 172.22.201.15
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.140.20.54
      JMX_PORT: 9999
      HOST_IP: 10.140.20.54
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_BROKER_ID: 1
#      KAFKA_HEAP_OPTS: "-Xmx8192M -Xms8192M"
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LISTENERS: PLAINTEXT://kafka-02:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.140.20.54:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo:2183

  kafka-03:
    container_name: kafka-03
    image: wurstmeister/kafka:2.13-2.8.1
    restart: always
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - "9094:9092"
    networks:
      kafka:
        ipv4_address: 172.22.201.16
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.140.20.54
      JMX_PORT: 9999
      HOST_IP: 10.140.20.54
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_BROKER_ID: 2
#      KAFKA_HEAP_OPTS: "-Xmx8192M -Xms8192M"
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LISTENERS: PLAINTEXT://kafka-03:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.140.20.54:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183

  kafka-manager:
    container_name: kafka-manager
    image: hlebalbau/kafka-manager:latest
    restart: always
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      - kafka-01
      - kafka-02
      - kafka-03
    ports:
      - "9001:9000"
    networks:
     kafka:
        ipv4_address: 172.22.201.17
    environment:
      ZK_HOSTS: 10.140.20.54:2181,10.140.20.54:2182,10.140.20.54:2183
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KAFKA_MANAGER_USERNAME: admin
      KAFKA_MANAGER_PASSWORD: admin

networks:
  kafka:
    name: kafka-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.201.0/24
          gateway: 172.22.201.1
